# -*- coding: utf-8 -*-
"""ipclass

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cy2n3MvhIvjpZBU5cg6E5E5tBXPPtiNr
"""

ip_address = input("Enter an IP address: ")

# Split IP para octetos
octets = ip_address.split(".")

# octetos a ints
first_octet = int(octets[0])
second_octet = int(octets[1])

iptype=""
ipclass=""

octets

if first_octet == 10:
  iptype="private"
elif first_octet == 172 and second_octet>= 16 and second_octet <= 31:
  iptype="private"
elif first_octet==192 and second_octet==168:
  iptype="private"
else: 
  iptype="public"

if first_octet >= 1 and first_octet <= 126:
  ipclass="class A"
elif first_octet >= 128 and first_octet <= 191:
  ipclass="class B"
elif first_octet >= 192 and first_octet <= 223:
  ipclass="class C"
elif first_octet >= 224 and first_octet <= 239:
  ipclass="class D"
else:
  ipclass="class E"

print("The IP address is " + iptype + ' and ' + ipclass)